# Generated by Django 3.1 on 2020-11-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_text', models.CharField(max_length=400)),
                ('event_host', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='event date')),
                ('end_event_date', models.DateTimeField(blank=True, null=True, verbose_name='end event date')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetupfinder.categories')),
            ],
        ),
    ]
