# Generated by Django 3.1 on 2020-10-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Name',
            new_name='Event',
        ),
    ]
