# Generated by Django 3.1 on 2020-10-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0002_auto_20201016_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
    ]
