# Generated by Django 3.1 on 2020-10-21 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0002_auto_20201016_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end event date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_host',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_text',
            field=models.CharField(max_length=400),
        ),
    ]
