# Generated by Django 3.1 on 2020-10-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0003_auto_20201021_1620'),
        ('meetupfinder', '0003_auto_20201021_1626'),
    ]

    operations = [
    ]
