# Generated by Django 3.1 on 2020-10-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0004_merge_20201021_1652'),
        ('meetupfinder', '0004_auto_20201022_0129'),
    ]

    operations = [
    ]
