# Generated by Django 3.1 on 2020-11-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0006_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='event',
        ),
    ]
