# Generated by Django 3.1.3 on 2020-11-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0009_event_attending_users'),
        ('meetupfinder', '0003_auto_20201105_1628'),
    ]

    operations = [
    ]
