# Generated by Django 3.1.3 on 2020-11-12 21:11

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0012_auto_20201112_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addresss',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
