# Generated by Django 3.1.3 on 2020-11-12 21:28

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0013_auto_20201112_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locate',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
