# Generated by Django 3.1.3 on 2020-11-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupfinder', '0014_event_locate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='addresss',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mpoly',
        ),
    ]
